create schema IF NOT Exists NCVoters;
use NCVoters;
CREATE USER IF NOT Exists 'user'@'localhost' IDENTIFIED BY 'password';
-- create table IF NOT Exists voters (`county_id` varchar(60), `county_desc` varchar(60),	`voter_reg_num` varchar(60),	`status_cd` varchar(60),	`voter_status_desc` varchar(60),	`reason_cd` varchar(60),	`voter_status_reason_desc` varchar(60),	`absent_ind` varchar(60),	`name_prefx_cd` varchar(60),	`last_name` varchar(60),	`first_name` varchar(60),	`middle_name` varchar(60),	`name_suffix_lbl` varchar(60),	`res_street_address` varchar(60),	`res_city_desc` varchar(60),	`state_cd` varchar(60),	`zip_code` varchar(60),	`mail_addr1` varchar(60),	`mail_addr2` varchar(60),	`mail_addr3` varchar(60),	`mail_addr4` varchar(60),	`mail_city` varchar(60),	`mail_state` varchar(60),	`mail_zipcode` varchar(60),	`full_phone_number` varchar(60),	`race_code` varchar(60),	`ethnic_code` varchar(60),	`party_cd` varchar(60),	`gender_code` varchar(60),	`birth_age` varchar(60),	`birth_state` varchar(60),	`drivers_lic` varchar(60),	`registr_dt` varchar(60),	`precinct_abbrv` varchar(60),	`precinct_desc` varchar(60),	`municipality_abbrv` varchar(60),	`municipality_desc` varchar(60),	`ward_abbrv` varchar(60),	`ward_desc` varchar(60),	`cong_dist_abbrv` varchar(60),	`super_court_abbrv` varchar(60),	`judic_dist_abbrv` varchar(60),	`nc_senate_abbrv` varchar(60),	`nc_house_abbrv` varchar(60),	`county_commiss_abbrv` varchar(60),	`county_commiss_desc` varchar(60),	`township_abbrv` varchar(60),	`township_desc` varchar(60),	`school_dist_abbrv` varchar(60),	`school_dist_desc` varchar(60),	`fire_dist_abbrv` varchar(60),	`fire_dist_desc` varchar(60),	`water_dist_abbrv` varchar(60),	`water_dist_desc` varchar(60),	`sewer_dist_abbrv` varchar(60),	`sewer_dist_desc` varchar(60),	`sanit_dist_abbrv` varchar(60),	`sanit_dist_desc` varchar(60),	`rescue_dist_abbrv` varchar(60),	`rescue_dist_desc` varchar(60),	`munic_dist_abbrv` varchar(60),	`munic_dist_desc` varchar(60),	`dist_1_abbrv` varchar(60),	`dist_1_desc` varchar(60),	`dist_2_abbrv` varchar(60),	`dist_2_desc` varchar(60),	`confidential_ind` varchar(60),	`age` varchar(60),	`ncid` varchar(60),	`vtd_abbrv` varchar(60),	`vtd_desc` varchar(60) );
create table IF NOT Exists voters  (`county_id`     smallint(2),	`county_desc`     varchar(15),	`voter_reg_num`             char(12),	`status_cd`     char(2),	`voter_status_desc`     varchar(25),	`reason_cd`     char(2),	`voter_status_reason_desc    ` varchar(60),	`absent_ind`     char(1),	`name_prefx_cd`             char(4),	`last_name`     char(25),	`first_name`     char(20),	`midl_name`     char(20),	`name_sufx_cd`             char(3),	`res_street_address`     varchar(63),	`res_city_desc`             varchar(60),	`state_cd`     char(2),	`zip_code`     char(9),	`mail_addr1`     varchar(40),	`mail_addr2`     varchar(40),	`mail_addr3`     varchar(40),	`mail_addr4`     varchar(40),	`mail_city`     varchar(30),	`mail_state`     char(2),	`mail_zipcode`             char(9),	`full_phone_number`     varchar(12),	`race_code`     char(3),	`ethnic_code`     char(3),	`party_cd`     char(3),	`gender_code`     varchar(1),	`birth_age`     int       (4),	`birth_place`     char(30),	`drivers_lic`     char        1 (2),	`registr_dt`     char(10),	`precinct_abbrv`             char(6),	`precinct_desc`             varchar(60),	`municipality_abbrv`     char(6),	`municipality_desc`     varchar(60),	`ward_abbrv`     char(6),	`ward_desc`     varchar(60),	`cong_dist_abbrv`             char(6),	`super_court_abbrv`     char(6),	`judic_dist_abbrv`     char(6),	`nc_senate_abbrv`             char(6),	`nc_house_abbrv`             char(6),	`county_commiss_abbrv`         char(6),	`county_commiss_desc`     varchar(60),	`township_abbrv`             char(6),	`township_desc`             varchar(60),	`school_dist_abbrv`     char(6),	`school_dist_desc`     varchar(60),	`fire_dist_abbrv`             char(6),	`fire_dist_desc`             varchar(60),	`water_dist_abbrv`     char(6),	`water_dist_desc`             varchar(60),	`sewer_dist_abbrv`     char(6),	`sewer_dist_desc`             varchar(60),	`sanit_dist_abbrv`     char(6),	`sanit_dist_desc`             varchar(60),	`rescue_dist_abbrv`     char(6),	`rescue_dist_desc`     varchar(60),	`munic_dist_abbrv`     char(6),	`munic_dist_desc`             varchar(60),	`dist_1_abbrv`             char(6),	`dist_1_desc`     varchar(60),	`dist_2_abbrv`             char(6),	`dist_2_desc`     varchar(60),	`Confidential_ind`     char(1),	`birth_year`     char        4(),	`ncid `             char (12),	`vtd_abbrv `     char (6),	`vtd_desc `     char (60) );

GRANT ALL PRIVILEGES ON NCVoters.voters TO 'user'@'localhost';
show grants for  'user'@'localhost';
use NCVoters;
truncate table voters;
# LOAD DATA local INFILE 'ncvoter_Statewide.txt' INTO TABLE voters FIELDS terminated BY ' ' enclosed by '"'  IGNORE 1 LINES ;
LOAD DATA local INFILE 'ncvoter_Statewide.txt' INTO TABLE voters FIELDS enclosed by '"'  IGNORE 1 LINES ;
select count(*) from voters;

